service: prisma-cloud--s3-service

custom:
  wsgi:
    app: app.app
    packRequirements: false  
  bucketName: myrandombucket

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    VARIABLE_1: supersecret99
    AWS_SECRET: RjrfT9zTOrg0Xgt56ViCYbztghLy6Hw1oUPGy93T
    deprecationNotificationMode: warn
  iam.role.statements:
    - Effect: Allow
      Action:
        - s3:*
        - cloudwatch:*"
        - ecr:GetAuthorizationToken
        - ecr:BatchCheckLayerAvailability
        - ecr:GetDownloadUrlForLayer
        - ecr:BatchGetImage
        - logs:CreateLogStream
        - logs:PutLogEvents
        - iam:PassRole
        - iam:ListAttachedUserPolicies
      Resource:
        - "*"

package:
  individually: true
  patterns:
    - app.py
    - requirements.txt
    - '!venv/**'
    - '!node_modules/**'
plugins:
  - serverless-s3-deploy
  - serverless-python-requirements
  - serverless-wsgi

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}    
        AccessControl: Private
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'



